[project]
name = "ai_resume_parser"
authors = [{ name = "Tejas", email = "hello@tejas.com" }]
description = "Upload resume, parse, store in Parsed Resume Data"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]

[tool.flit.module]
name = "ai_resume_parser"

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"
