[project]
name = "whatsapp_integration"
authors = [
    { name = "Tejas", email = "hello@tejas.com"}
]
description = "WhatsApp Cloud API integration for Frappe / ERPNext"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe~=15.0.0" # Installed and managed by bench.
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]

[deploy.dependencies.apt]
packages = []
